package emoji

// catalog is a curated set of workplace-relevant emoji. It is intentionally
// small but covers the common Slack status use-cases.
var catalog = []Emoji{
	{Name: "calendar", Char: "📅", Keywords: []string{"appointment", "meeting", "schedule"}},
	{Name: "spiral_calendar_pad", Char: "🗓", Keywords: []string{"appointment", "plan", "schedule"}},
	{Name: "date", Char: "📆", Keywords: []string{"appointment", "date"}},
	{Name: "clock1", Char: "🕐", Keywords: []string{"time", "clock"}},
	{Name: "hourglass", Char: "⌛", Keywords: []string{"waiting", "time", "duration"}},
	{Name: "watch", Char: "⌚", Keywords: []string{"time", "clock"}},
	{Name: "office", Char: "🏢", Keywords: []string{"office", "work", "building"}},
	{Name: "house", Char: "🏠", Keywords: []string{"home"}},
	{Name: "house_with_garden", Char: "🏡", Keywords: []string{"homeoffice", "home", "remote"}},
	{Name: "desktop_computer", Char: "🖥", Keywords: []string{"computer", "work", "homeoffice"}},
	{Name: "laptop", Char: "💻", Keywords: []string{"computer", "work", "homeoffice", "coding"}},
	{Name: "keyboard", Char: "⌨", Keywords: []string{"typing", "coding"}},
	{Name: "iphone", Char: "📱", Keywords: []string{"phone", "mobile"}},
	{Name: "telephone", Char: "☎", Keywords: []string{"phone", "call"}},
	{Name: "phone", Char: "📞", Keywords: []string{"phone", "call"}},
	{Name: "headphones", Char: "🎧", Keywords: []string{"music", "focus", "huddle"}},
	{Name: "microphone", Char: "🎤", Keywords: []string{"microphone", "meeting", "call"}},
	{Name: "studio_microphone", Char: "🎙", Keywords: []string{"podcast", "call"}},
	{Name: "video_camera", Char: "📹", Keywords: []string{"video", "meeting", "call"}},
	{Name: "movie_camera", Char: "🎥", Keywords: []string{"video", "call"}},
	{Name: "speech_balloon", Char: "💬", Keywords: []string{"chat", "talk"}},
	{Name: "left_speech_bubble", Char: "🗨", Keywords: []string{"chat", "talk"}},
	{Name: "memo", Char: "📝", Keywords: []string{"note", "write"}},
	{Name: "pencil2", Char: "✏", Keywords: []string{"note", "write"}},
	{Name: "pushpin", Char: "📌", Keywords: []string{"pin", "important"}},
	{Name: "round_pushpin", Char: "📍", Keywords: []string{"location"}},
	{Name: "paperclip", Char: "📎", Keywords: []string{"attachment"}},
	{Name: "file_folder", Char: "📁", Keywords: []string{"folder", "files"}},
	{Name: "open_file_folder", Char: "📂", Keywords: []string{"folder", "files"}},
	{Name: "bookmark", Char: "🔖", Keywords: []string{"bookmark", "save"}},
	{Name: "coffee", Char: "☕", Keywords: []string{"coffee", "break", "pause"}},
	{Name: "tea", Char: "🍵", Keywords: []string{"tea", "break"}},
	{Name: "green_salad", Char: "🥗", Keywords: []string{"lunch", "break", "salad"}},
	{Name: "hamburger", Char: "🍔", Keywords: []string{"lunch", "food"}},
	{Name: "pizza", Char: "🍕", Keywords: []string{"lunch", "food"}},
	{Name: "fork_and_knife", Char: "🍴", Keywords: []string{"food", "lunch", "break"}},
	{Name: "beers", Char: "🍻", Keywords: []string{"afterwork", "beer", "cheers"}},
	{Name: "tropical_drink", Char: "🍹", Keywords: []string{"holiday", "vacation", "cocktail"}},
	{Name: "cake", Char: "🍰", Keywords: []string{"birthday", "cake"}},
	{Name: "dart", Char: "🎯", Keywords: []string{"focus", "goal", "target"}},
	{Name: "rocket", Char: "🚀", Keywords: []string{"launch", "start", "deploy"}},
	{Name: "zap", Char: "⚡", Keywords: []string{"fast", "energy"}},
	{Name: "fire", Char: "🔥", Keywords: []string{"hot", "important", "urgent"}},
	{Name: "star", Char: "⭐", Keywords: []string{"star", "favorite"}},
	{Name: "sparkles", Char: "✨", Keywords: []string{"new", "shine"}},
	{Name: "bulb", Char: "💡", Keywords: []string{"idea", "tip"}},
	{Name: "gear", Char: "⚙", Keywords: []string{"settings", "work", "config"}},
	{Name: "wrench", Char: "🔧", Keywords: []string{"work", "fix", "repair"}},
	{Name: "hammer_and_wrench", Char: "🛠", Keywords: []string{"work", "build", "tools"}},
	{Name: "computer_mouse", Char: "🖱", Keywords: []string{"mouse", "computer"}},
	{Name: "shield", Char: "🛡", Keywords: []string{"security", "shield"}},
	{Name: "lock", Char: "🔒", Keywords: []string{"locked", "busy", "dnd", "do not disturb"}},
	{Name: "no_entry", Char: "⛔", Keywords: []string{"do not disturb", "busy", "stop"}},
	{Name: "no_bell", Char: "🔕", Keywords: []string{"mute", "silent", "do not disturb"}},
	{Name: "bell", Char: "🔔", Keywords: []string{"notification", "bell"}},
	{Name: "mute", Char: "🔇", Keywords: []string{"mute", "silent"}},
	{Name: "loud_sound", Char: "🔊", Keywords: []string{"loud", "sound"}},
	{Name: "eye", Char: "👀", Keywords: []string{"watch", "review", "look"}},
	{Name: "mag", Char: "🔍", Keywords: []string{"search", "review"}},
	{Name: "mag_right", Char: "🔎", Keywords: []string{"search"}},
	{Name: "chart_with_upwards_trend", Char: "📈", Keywords: []string{"growth", "report"}},
	{Name: "bar_chart", Char: "📊", Keywords: []string{"statistics", "report", "chart"}},
	{Name: "clipboard", Char: "📋", Keywords: []string{"list", "task", "todo"}},
	{Name: "spiral_note_pad", Char: "🗒", Keywords: []string{"note"}},
	{Name: "triangular_flag_on_post", Char: "🚩", Keywords: []string{"flag", "important"}},
	{Name: "checkered_flag", Char: "🏁", Keywords: []string{"done", "finish", "goal"}},
	{Name: "white_check_mark", Char: "✅", Keywords: []string{"done", "ok", "complete"}},
	{Name: "heavy_check_mark", Char: "✔", Keywords: []string{"done", "ok"}},
	{Name: "x", Char: "❌", Keywords: []string{"no", "away", "cancel"}},
	{Name: "warning", Char: "⚠", Keywords: []string{"warning", "attention"}},
	{Name: "question", Char: "❓", Keywords: []string{"question", "help"}},
	{Name: "grey_question", Char: "❔", Keywords: []string{"question"}},
	{Name: "exclamation", Char: "❗", Keywords: []string{"important", "attention"}},
	{Name: "information_source", Char: "ℹ", Keywords: []string{"info", "note"}},
	{Name: "sos", Char: "🆘", Keywords: []string{"help", "urgent", "emergency"}},
	{Name: "red_circle", Char: "🔴", Keywords: []string{"red", "busy"}},
	{Name: "large_green_circle", Char: "🟢", Keywords: []string{"green", "available"}},
	{Name: "large_yellow_circle", Char: "🟡", Keywords: []string{"yellow", "away"}},
	{Name: "white_circle", Char: "⚪", Keywords: []string{"white", "offline"}},
	{Name: "hourglass_flowing_sand", Char: "⏳", Keywords: []string{"waiting", "duration"}},
	{Name: "alarm_clock", Char: "⏰", Keywords: []string{"alarm", "reminder", "appointment"}},
	{Name: "stopwatch", Char: "⏱", Keywords: []string{"time", "duration", "timer"}},
	{Name: "timer_clock", Char: "⏲", Keywords: []string{"timer", "time"}},
	{Name: "bed", Char: "🛏", Keywords: []string{"sick", "bed", "rest"}},
	{Name: "face_with_thermometer", Char: "🤒", Keywords: []string{"sick", "fever"}},
	{Name: "mask", Char: "😷", Keywords: []string{"sick", "mask"}},
	{Name: "nauseated_face", Char: "🤢", Keywords: []string{"sick", "ill"}},
	{Name: "crutch", Char: "🩼", Keywords: []string{"sick", "injured"}},
	{Name: "airplane", Char: "✈", Keywords: []string{"travel", "holiday", "flight"}},
	{Name: "takeoff", Char: "🛫", Keywords: []string{"travel", "departure"}},
	{Name: "car", Char: "🚗", Keywords: []string{"commute", "car", "driving"}},
	{Name: "oncoming_automobile", Char: "🚘", Keywords: []string{"commute", "car"}},
	{Name: "bus", Char: "🚌", Keywords: []string{"commute", "bus"}},
	{Name: "train", Char: "🚆", Keywords: []string{"commute", "train"}},
	{Name: "bike", Char: "🚲", Keywords: []string{"bike", "commute"}},
	{Name: "walking", Char: "🚶", Keywords: []string{"walking", "commute"}},
	{Name: "runner", Char: "🏃", Keywords: []string{"running", "sport", "fast"}},
	{Name: "palmtree", Char: "🌴", Keywords: []string{"holiday", "vacation"}},
	{Name: "sunny", Char: "☀", Keywords: []string{"sun", "holiday", "weather"}},
	{Name: "beach_with_umbrella", Char: "🏖", Keywords: []string{"holiday", "beach", "vacation"}},
	{Name: "snowflake", Char: "❄", Keywords: []string{"snow", "winter"}},
	{Name: "rainbow", Char: "🌈", Keywords: []string{"rainbow"}},
	{Name: "mortar_board", Char: "🎓", Keywords: []string{"training", "learning", "study"}},
	{Name: "books", Char: "📚", Keywords: []string{"learning", "books", "study"}},
	{Name: "book", Char: "📖", Keywords: []string{"reading", "book"}},
	{Name: "blue_book", Char: "📘", Keywords: []string{"reading", "book"}},
	{Name: "brain", Char: "🧠", Keywords: []string{"thinking", "focus", "brain"}},
	{Name: "muscle", Char: "💪", Keywords: []string{"sport", "strong", "gym"}},
	{Name: "lotus_position", Char: "🧘", Keywords: []string{"meditation", "break", "yoga"}},
	{Name: "handshake", Char: "🤝", Keywords: []string{"meeting", "deal", "together"}},
	{Name: "wave", Char: "👋", Keywords: []string{"hello", "hi", "bye"}},
	{Name: "raised_hand", Char: "✋", Keywords: []string{"hand", "stop", "hello"}},
	{Name: "ok_hand", Char: "👌", Keywords: []string{"ok", "good"}},
	{Name: "thumbsup", Char: "👍", Keywords: []string{"good", "ok", "like"}},
	{Name: "thumbsdown", Char: "👎", Keywords: []string{"bad", "dislike"}},
	{Name: "clap", Char: "👏", Keywords: []string{"applause", "bravo"}},
	{Name: "pray", Char: "🙏", Keywords: []string{"thanks", "please"}},
	{Name: "sunglasses", Char: "😎", Keywords: []string{"cool", "relaxed"}},
	{Name: "smile", Char: "😄", Keywords: []string{"smile", "happy"}},
	{Name: "slightly_smiling_face", Char: "🙂", Keywords: []string{"smile"}},
	{Name: "upside_down_face", Char: "🙃", Keywords: []string{"fun"}},
	{Name: "thinking_face", Char: "🤔", Keywords: []string{"thinking"}},
	{Name: "face_with_rolling_eyes", Char: "🙄", Keywords: []string{"eyeroll"}},
	{Name: "sleeping", Char: "😴", Keywords: []string{"sleep", "tired"}},
	{Name: "sleeping_accommodation", Char: "🛌", Keywords: []string{"sleep", "bed"}},
	{Name: "sweat_smile", Char: "😅", Keywords: []string{"stress", "sweat"}},
	{Name: "scream", Char: "😱", Keywords: []string{"shock", "stress"}},
	{Name: "rotating_light", Char: "🚨", Keywords: []string{"alarm", "incident", "urgent"}},
	{Name: "fire_engine", Char: "🚒", Keywords: []string{"emergency"}},
	{Name: "toilet", Char: "🚽", Keywords: []string{"toilet", "bathroom", "break"}},
	{Name: "door", Char: "🚪", Keywords: []string{"door", "away"}},
	{Name: "potted_plant", Char: "🪴", Keywords: []string{"plant", "office"}},
	{Name: "deciduous_tree", Char: "🌳", Keywords: []string{"tree", "outside"}},
	{Name: "earth_africa", Char: "🌍", Keywords: []string{"world", "remote", "global"}},
	{Name: "globe_with_meridians", Char: "🌐", Keywords: []string{"world", "remote", "web"}},
	{Name: "satellite", Char: "📡", Keywords: []string{"remote", "network"}},
	{Name: "speech_left", Char: "🗨", Keywords: []string{"feedback"}},
	{Name: "moneybag", Char: "💰", Keywords: []string{"money", "budget"}},
	{Name: "credit_card", Char: "💳", Keywords: []string{"payment"}},
	{Name: "package", Char: "📦", Keywords: []string{"package", "delivery", "release"}},
	{Name: "label", Char: "🏷", Keywords: []string{"tag", "label"}},
	{Name: "megaphone", Char: "📣", Keywords: []string{"announcement"}},
	{Name: "loudspeaker", Char: "📢", Keywords: []string{"announcement"}},
	{Name: "eyes", Char: "👁", Keywords: []string{"watch", "look"}},
	{Name: "point_up", Char: "☝", Keywords: []string{"point", "note"}},
	{Name: "back", Char: "🔙", Keywords: []string{"back", "return"}},
	{Name: "soon", Char: "🔜", Keywords: []string{"soon"}},
	{Name: "end", Char: "🔚", Keywords: []string{"end"}},
	{Name: "top", Char: "🔝", Keywords: []string{"top"}},
	{Name: "heavy_plus_sign", Char: "➕", Keywords: []string{"plus", "add"}},
	{Name: "heavy_minus_sign", Char: "➖", Keywords: []string{"minus", "remove"}},
	{Name: "arrows_clockwise", Char: "🔄", Keywords: []string{"refresh", "sync", "reload"}},
	{Name: "inbox_tray", Char: "📥", Keywords: []string{"inbox"}},
	{Name: "outbox_tray", Char: "📤", Keywords: []string{"outbox"}},
	{Name: "envelope", Char: "✉", Keywords: []string{"mail", "email"}},
	{Name: "e-mail", Char: "📧", Keywords: []string{"mail", "email"}},
	{Name: "pager", Char: "📟", Keywords: []string{"oncall", "pager"}},
	{Name: "hospital", Char: "🏥", Keywords: []string{"doctor", "hospital"}},
	{Name: "stethoscope", Char: "🩺", Keywords: []string{"doctor"}},
	{Name: "pill", Char: "💊", Keywords: []string{"medicine", "sick"}},
	{Name: "dog", Char: "🐶", Keywords: []string{"dog"}},
	{Name: "cat", Char: "🐱", Keywords: []string{"cat"}},
	{Name: "baby", Char: "👶", Keywords: []string{"parental leave", "baby"}},
	{Name: "family", Char: "👨‍👩‍👧", Keywords: []string{"family"}},
	{Name: "heart", Char: "❤", Keywords: []string{"heart", "love"}},
	{Name: "green_heart", Char: "💚", Keywords: []string{"heart", "green"}},
	{Name: "tada", Char: "🎉", Keywords: []string{"party", "celebrate"}},
	{Name: "gift", Char: "🎁", Keywords: []string{"gift", "present"}},
	{Name: "balloon", Char: "🎈", Keywords: []string{"party"}},
	{Name: "trophy", Char: "🏆", Keywords: []string{"win", "trophy", "success"}},
	{Name: "medal_sports", Char: "🏅", Keywords: []string{"medal", "success"}},
	{Name: "sparkling_heart", Char: "💖", Keywords: []string{"heart"}},
	{Name: "cloud", Char: "☁", Keywords: []string{"cloud", "remote"}},
	{Name: "hot_beverage", Char: "☕", Keywords: []string{"coffee", "tea"}},
	{Name: "thought_balloon", Char: "💭", Keywords: []string{"thinking"}},
	{Name: "dizzy", Char: "💫", Keywords: []string{"dizzy", "stress"}},
	{Name: "zzz", Char: "💤", Keywords: []string{"sleep", "tired", "offline"}},
	{Name: "pirate_flag", Char: "🏴‍☠", Keywords: []string{"focus", "dnd", "busy"}},
}
